#!/bin/bash
# Author : Valentin Urcun
# Displays the current sound volume and screen brightness

# volume level
volume=$(amixer -D pulse get Master | awk -F 'Left:|[][]' 'BEGIN {RS=""}{ print $3 }')

# muted status
muted=$(pacmd list-sinks | awk '/muted/ { print $2 }')

# brightness level
light=$(xbacklight -getf | awk '{print ($0-int($0)>0)?int($0)+1:int($0)}')


# the brightness icon depends of the %
if [ "$light" -lt "6" ]
then
	iconLight=
else
	if [ $light -lt 31 ]
	then
		iconLight=
	else
		if  [ $light -lt 66 ]
		then 
			iconLight=
		else
			if  [ $light -lt 96 ]
			then
				iconLight=
			else 
				iconLight=
			fi
		fi
	fi
fi


# the volume icon depends of the % and the muted status
if [ "$muted" = "yes" ]
then
	iconSound=
else
	if [ "$volume" = "5%" ] || [ "$volume" = "0%" ]
	then
		iconSound=
	else
		if [ "$volume" = "100%" ] || [ "$volume" = "90%" ] || [ "$volume" = "80%" ] || [ "$volume" = "70%" ] || [ "$volume" = "60%" ] || [ "$volume" = "50%" ]
		then
			iconSound=
		else
			iconSound=
		fi
	fi
fi


# sexy output
#echo "%{F+}%{F#f9f1af}${iconSound} %{F+}$volume %{F+} %{F#f9f1af}${iconLight} %{F+}$light%"
#echo "%{F+}%{F#f9f1af}$iconSound %{F+}$volume"
if [ "$muted" = "yes" ]
then
    echo "%{F#f9f1af}$iconSound $iconLight $light"
else
    echo "%{F#f9f1af}$iconSound $volume $iconLight $light"
fi
